debug: true

server:
  port: 9005

eureka:
  enabled: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true

spring.thymeleaf.cache: false
